import { AIServiceConfig } from '../types';

export interface HarumiGenerationResult {
  code: string;
  explanation: string;
  isMock: boolean;
  provider: 'mistral' | 'gemini' | 'mock';
  model: string;
  version: 'Lua 5.1';
  timestamp: number;
}

const DEFAULT_SYSTEM_PROMPT = `You are HARUMI GPT, an expert Lua 5.1 code generator specializing in Blockman GO (BMGO) client scripts and the GMHelper engine.
Rules:
1. Generate strictly Lua 5.1 compatible code. Never use Lua 5.2/5.3/5.4 features (no bitwise operators like & |, no floor division operator, no goto, no _ENV).
2. Utilize authentic Blockman GO client structures when requested:
   - PlayerManager:getClientPlayer().Player
   - ClientHelper.putBoolPrefs(key, bool), ClientHelper.putFloatPrefs(key, float), ClientHelper.putIntPrefs(key, int)
   - UIHelper.showToast("^00FF00[Text]")
   - VectorUtil.newVector3(x, y, z)
   - LuaTimer:scheduleTimer(fn, delayMs, repeat)
   - PacketSender:getSender():sendRebirth()
3. Return clean, robust Lua 5.1 code that can immediately be reviewed, saved, and executed in the BMGO Executor.
4. Output only Lua 5.1 code in a markdown block followed by a brief explanation.`;

export class HarumiGPTService {
  private config: AIServiceConfig = {
    provider: 'mistral',
    apiKey: '',
    mistralApiKey: '',
    geminiApiKey: '',
    useMock: false,
    model: 'codestral-latest',
    temperature: 0.2,
    systemPrompt: DEFAULT_SYSTEM_PROMPT
  };

  constructor() {
    this.loadConfig();
  }

  public getConfig(): AIServiceConfig {
    return { ...this.config };
  }

  public updateConfig(newConfig: Partial<AIServiceConfig>): void {
    this.config = { ...this.config, ...newConfig };
    this.saveConfig();
  }

  private loadConfig(): void {
    try {
      const saved = localStorage.getItem('bmgo_harumi_config');
      if (saved) {
        const parsed = JSON.parse(saved);
        this.config = {
          ...this.config,
          ...parsed,
          mistralApiKey: parsed.mistralApiKey || ''
        };
      }
    } catch {}
  }

  private saveConfig(): void {
    try {
      localStorage.setItem('bmgo_harumi_config', JSON.stringify(this.config));
    } catch {}
  }

  public async generate(prompt: string): Promise<HarumiGenerationResult> {
    const trimmed = prompt.trim();
    if (!trimmed) {
      throw new Error('Prompt cannot be empty');
    }

    const provider = this.config.provider || 'mistral';

    if (provider === 'mistral' && !this.config.useMock && (this.config.mistralApiKey || this.config.apiKey)) {
      const key = this.config.mistralApiKey || this.config.apiKey;
      try {
        const response = await fetch('https://api.mistral.ai/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${key}`
          },
          body: JSON.stringify({
            model: this.config.model || 'codestral-latest',
            messages: [
              {
                role: 'system',
                content: this.config.systemPrompt
              },
              {
                role: 'user',
                content: `Generate a Lua 5.1 script for Blockman GO:\n${trimmed}\n\nStrict output format:\n\`\`\`lua\n-- code here\n\`\`\`\nBrief explanation of functions used.`
              }
            ],
            temperature: this.config.temperature || 0.2
          })
        });

        if (!response.ok) {
          const errData = await response.json().catch(() => ({}));
          throw new Error(errData?.message || `Mistral API responded with status ${response.status}`);
        }

        const data = await response.json();
        const content = data.choices?.[0]?.message?.content || '';

        const codeMatch = content.match(/```lua([\s\S]*?)```/) || content.match(/```([\s\S]*?)```/);
        const code = codeMatch ? codeMatch[1].trim() : content.trim();
        const explanation = content.replace(/```lua[\s\S]*?```/g, '').replace(/```[\s\S]*?```/g, '').trim() || 'Lua 5.1 script generated by Mistral AI.';

        return {
          code,
          explanation,
          isMock: false,
          provider: 'mistral',
          model: this.config.model || 'codestral-latest',
          version: 'Lua 5.1',
          timestamp: Date.now()
        };
      } catch (err: any) {
        return this.generateMockLua(trimmed, `Mistral Notice: ${err?.message || 'Using fallback synthesis'}`);
      }
    }

    if (provider === 'gemini' && !this.config.useMock && this.config.geminiApiKey && this.config.geminiApiKey !== 'YOUR_API_KEY_HERE') {
      try {
        const { GoogleGenAI } = await import('@google/genai');
        const ai = new GoogleGenAI({ apiKey: this.config.geminiApiKey });
        const response = await ai.models.generateContent({
          model: this.config.model || 'gemini-2.5-flash',
          contents: `${this.config.systemPrompt}\n\nTask: Generate a Lua 5.1 script for Blockman GO:\n${trimmed}\n\nReturn format:\n\`\`\`lua\n-- code here\n\`\`\`\nExplanation.`
        });

        const text = response.text || '';
        const codeMatch = text.match(/```lua([\s\S]*?)```/) || text.match(/```([\s\S]*?)```/);
        const code = codeMatch ? codeMatch[1].trim() : text.trim();
        const explanation = text.replace(/```lua[\s\S]*?```/g, '').replace(/```[\s\S]*?```/g, '').trim() || 'Lua 5.1 script synthesized by Gemini.';

        return {
          code,
          explanation,
          isMock: false,
          provider: 'gemini',
          model: this.config.model || 'gemini-2.5-flash',
          version: 'Lua 5.1',
          timestamp: Date.now()
        };
      } catch (err: any) {
        return this.generateMockLua(trimmed, `Gemini Notice: ${err?.message || 'Reverting to offline generator'}`);
      }
    }

    await new Promise((res) => setTimeout(res, 400));
    return this.generateMockLua(trimmed);
  }

  private generateMockLua(prompt: string, note?: string): HarumiGenerationResult {
    const p = prompt.toLowerCase();

    if (p.includes('fly') || p.includes('parachute') || p.includes('glide')) {
      const code = `local player = PlayerManager:getClientPlayer()
if player and player.Player then
    player.Player:setAllowFlying(true)
    player.Player:setFlying(true)
    local moveDir = VectorUtil.newVector3(0.0, 1.35, 0.0)
    player.Player:moveEntity(moveDir)
    player.Player:setSpeedAdditionLevel(150000)
    UIHelper.showToast("^00FF00Harumi Fly: ACTIVE")
else
    UIHelper.showToast("^FF0000Failed to acquire client player")
end`;
      return {
        code,
        explanation: `${note ? note + '\n\n' : ''}Configures player entity flying capability in Lua 5.1, calculates upward motion vector, and activates 150k speed boost.`,
        isMock: true,
        provider: 'mock',
        model: 'harumi-offline-5.1',
        version: 'Lua 5.1',
        timestamp: Date.now()
      };
    }

    if (p.includes('reach') || p.includes('distance') || p.includes('hitbox')) {
      const code = `ClientHelper.putFloatPrefs("BlockReachDistance", 999.0)
ClientHelper.putFloatPrefs("EntityReachDistance", 12.0)
local players = PlayerManager:getPlayers()
local client = PlayerManager:getClientPlayer()
for _, pl in ipairs(players) do
    if pl ~= client and pl.Player then
        pl.Player.width = 8.0
        pl.Player.height = 8.0
        pl.Player.lenght = 8.0
    end
end
UIHelper.showToast("^00FFDDExtended Reach & Hitbox: 999 blocks")`;
      return {
        code,
        explanation: `${note ? note + '\n\n' : ''}Overrides ClientHelper BlockReachDistance and expands all enemy player entity bounding boxes to 8.0 dimensions.`,
        isMock: true,
        provider: 'mock',
        model: 'harumi-offline-5.1',
        version: 'Lua 5.1',
        timestamp: Date.now()
      };
    }

    if (p.includes('bedwars') || p.includes('bw') || p.includes('bypass')) {
      const code = `ClientHelper.putIntPrefs("ClientHelper.RunLimitCheck", 0)
ClientHelper.putIntPrefs("ClientHelper.SprintLimitCheck", 0)
ClientHelper.putBoolPrefs("banClickCD", true)
ClientHelper.putBoolPrefs("RemoveClickCD", true)
local client = PlayerManager:getClientPlayer()
if client and client.Player then
    client.Player:setIntProperty("bedWarAttackCD", 0)
end
UIHelper.showToast("^00FF00BedWars Full Bypass Enabled")`;
      return {
        code,
        explanation: `${note ? note + '\n\n' : ''}Bypasses BedWars sprint validation and removes attack cooldown timers for immediate combo hits.`,
        isMock: true,
        provider: 'mock',
        model: 'harumi-offline-5.1',
        version: 'Lua 5.1',
        timestamp: Date.now()
      };
    }

    if (p.includes('click') || p.includes('autoclick') || p.includes('cps')) {
      const code = `local autoClickTimer = nil
local active = true
UIHelper.showToast("^00FF00AutoClicker Loop Started")

autoClickTimer = LuaTimer:scheduleTimer(function()
    if active then
        CGame.Instance():handleTouchClick(770, 370)
    end
end, 25, -1)`;
      return {
        code,
        explanation: `${note ? note + '\n\n' : ''}Schedules a 25ms repeating LuaTimer that triggers touch click events at screen center (770, 370).`,
        isMock: true,
        provider: 'mock',
        model: 'harumi-offline-5.1',
        version: 'Lua 5.1',
        timestamp: Date.now()
      };
    }

    if (p.includes('esp') || p.includes('tracer') || p.includes('aimbot') || p.includes('radar')) {
      const code = `local me = PlayerManager:getClientPlayer()
if me and me.Player then
    me.Player:deleteAllGuideArrow()
    local allPlayers = PlayerManager:getPlayers()
    for _, target in pairs(allPlayers) do
        if target ~= me and target.Player then
            local pos = target.Player:getPosition()
            me.Player:addGuideArrow(pos)
        end
    end
    UIHelper.showToast("^00FFDDTracer Arrows Updated")
end`;
      return {
        code,
        explanation: `${note ? note + '\n\n' : ''}Iterates over all active player entities in the world and draws Blockman GO directional navigation arrows to their positions.`,
        isMock: true,
        provider: 'mock',
        model: 'harumi-offline-5.1',
        version: 'Lua 5.1',
        timestamp: Date.now()
      };
    }

    const safeTitle = prompt.replace(/"/g, '\\"');
    const code = `local scriptName = "${safeTitle}"
print("BMGO Harumi GPT Lua 5.1 Runtime Initiated: " .. scriptName)

local player = PlayerManager:getClientPlayer()
if player then
    local currentHp = player.Player and player.Player:getHp() or 100
    print("Active client player validated. HP: " .. tostring(currentHp))
    UIHelper.showToast("^00FF00[Harumi] " .. scriptName .. " applied!")
else
    UIHelper.showToast("^FF0000[Harumi] Waiting for Game instance...")
end`;

    return {
      code,
      explanation: `${note ? note + '\n\n' : ''}Synthesized custom Lua 5.1 logic for "${prompt}" adhering to GMHelper runtime patterns with PlayerManager client validation.`,
      isMock: true,
      provider: 'mock',
      model: 'harumi-offline-5.1',
      version: 'Lua 5.1',
      timestamp: Date.now()
    };
  }
}

export const HarumiGPT = new HarumiGPTService();
