import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Play,
  Copy,
  Check,
  Save,
  Trash2,
  Terminal,
  ExternalLink,
  Code2,
  ArrowDownToLine,
  Cpu,
  Zap,
  Sliders
} from 'lucide-react';
import { HarumiGPT } from '../services/harumiGpt';
import { StorageService } from '../services/storage';
import { AIServiceConfig } from '../types';

interface DashboardHarumiProps {
  onLoadScriptToExecutor: (code: string) => void;
  onOpenExecutor: () => void;
}

export const DashboardHarumi: React.FC<DashboardHarumiProps> = ({
  onLoadScriptToExecutor,
  onOpenExecutor
}) => {
  const [prompt, setPrompt] = useState<string>('');
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const [explanation, setExplanation] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>('');
  const [copied, setCopied] = useState<boolean>(false);
  const [savedSuccess, setSavedSuccess] = useState<boolean>(false);
  const [aiConfig, setAiConfig] = useState<AIServiceConfig>(HarumiGPT.getConfig());
  const [activeModelTag, setActiveModelTag] = useState<string>('Mistral Codestral');

  useEffect(() => {
    setAiConfig(HarumiGPT.getConfig());
  }, []);

  const presets = [
    {
      label: 'BedWars Auto-Bridge',
      prompt: 'Make a Lua 5.1 script for BedWars quickblock bridge with sprint check bypass'
    },
    {
      label: 'Anti-Cooldown Combat',
      prompt: 'Make a Lua 5.1 script that disables attack delay (BanClickCD) and sets reach to 999'
    },
    {
      label: 'DevFly & Glider',
      prompt: 'Make a Lua 5.1 script that activates player flying and applies 150000 speed'
    },
    {
      label: 'ESP Tracer Arrows',
      prompt: 'Make a Lua 5.1 script that draws guide navigation arrows to all active players'
    },
    {
      label: 'Fast Break 40k Blocks',
      prompt: 'Make a Lua 5.1 script that iterates through 40000 blocks and sets hardness to 0'
    }
  ];

  const handleProviderChange = (provider: 'mistral' | 'gemini' | 'mock') => {
    const updated: Partial<AIServiceConfig> = {
      provider,
      useMock: provider === 'mock',
      model: provider === 'mistral' ? 'codestral-latest' : 'gemini-2.5-flash'
    };
    HarumiGPT.updateConfig(updated);
    setAiConfig(HarumiGPT.getConfig());
  };

  const handleModelChange = (model: string) => {
    HarumiGPT.updateConfig({ model });
    setAiConfig(HarumiGPT.getConfig());
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsLoading(true);
    setErrorMessage('');
    setSavedSuccess(false);

    try {
      const res = await HarumiGPT.generate(prompt);
      setGeneratedCode(res.code);
      setExplanation(res.explanation);
      setActiveModelTag(
        res.provider === 'mistral'
          ? `Mistral (${res.model})`
          : res.provider === 'gemini'
          ? `Gemini (${res.model})`
          : 'Offline Mock'
      );
    } catch (err: any) {
      setErrorMessage(err?.message || 'Failed to generate Lua 5.1 script');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = () => {
    if (!generatedCode) return;
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleInsertIntoExecutor = () => {
    if (!generatedCode) return;
    onLoadScriptToExecutor(generatedCode);
    onOpenExecutor();
  };

  const handleSaveToScripts = () => {
    if (!generatedCode) return;
    const title = prompt.length > 25 ? prompt.substring(0, 25) + '...' : prompt;
    StorageService.addScript({
      title: `AI: ${title}`,
      description: explanation || 'Generated by Harumi GPT Lua 5.1',
      code: generatedCode,
      category: 'AI Generated',
      tags: ['Lua5.1', 'HarumiGPT', aiConfig.provider],
      author: aiConfig.provider === 'mistral' ? 'MISTRAL CODESTRAL' : 'HARUMI GPT',
      favorite: false
    });
    setSavedSuccess(true);
    setTimeout(() => setSavedSuccess(false), 2500);
  };

  const handleClear = () => {
    setPrompt('');
    setGeneratedCode('');
    setExplanation('');
    setErrorMessage('');
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-2xl bg-slate-900/80 border border-cyan-500/30">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-cyan-400" />
            <h2 className="text-xl font-extrabold text-white tracking-wide">HARUMI GPT CODE MAKER</h2>
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-400 border border-cyan-800">
              {aiConfig.provider === 'mistral' ? 'Mistral AI Connected' : 'Lua 5.1 Strict'}
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Autonomous natural-language to Lua 5.1 Blockman GO code synthesizer powered by Mistral AI and Codestral.
          </p>
        </div>

        <button
          onClick={handleClear}
          className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer self-start sm:self-auto"
        >
          <Trash2 className="w-3.5 h-3.5" />
          <span>Reset All</span>
        </button>
      </div>

      <div className="p-4 rounded-2xl bg-slate-900/60 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold text-slate-300">AI Provider Engine:</span>
          <div className="flex items-center gap-1.5">
            {[
              { id: 'mistral', label: 'Mistral AI (Codestral)' },
              { id: 'gemini', label: 'Google Gemini' },
              { id: 'mock', label: 'Offline Engine' }
            ].map((p) => (
              <button
                key={p.id}
                onClick={() => handleProviderChange(p.id as any)}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                  aiConfig.provider === p.id
                    ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                    : 'bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800'
                }`}
              >
                {p.label}
              </button>
            ))}
          </div>
        </div>

        {aiConfig.provider === 'mistral' && (
          <div className="flex items-center gap-2">
            <span className="text-[11px] text-slate-400">Model:</span>
            <select
              value={aiConfig.model}
              onChange={(e) => handleModelChange(e.target.value)}
              className="bg-slate-950 border border-slate-800 text-xs text-cyan-300 rounded-lg px-2.5 py-1 outline-none"
            >
              <option value="codestral-latest">codestral-latest (Fastest Lua)</option>
              <option value="mistral-small-latest">mistral-small-latest</option>
              <option value="mistral-large-latest">mistral-large-latest</option>
              <option value="open-mistral-7b">open-mistral-7b</option>
            </select>
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-slate-900/60 border border-slate-800/80 rounded-2xl p-5 space-y-3">
            <label className="text-xs font-bold text-slate-200 uppercase tracking-wider block">
              Natural Language Prompt
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Describe what your Blockman GO script should do (e.g. 'Make a Lua 5.1 script that loops player position and sets jump height to 1')..."
              rows={5}
              className="w-full p-3 text-xs rounded-xl bg-slate-950 border border-slate-800 text-white outline-none focus:border-cyan-500/50 resize-none font-sans leading-relaxed"
            />

            <button
              onClick={handleGenerate}
              disabled={isLoading || !prompt.trim()}
              className="w-full py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-slate-950 font-extrabold text-xs flex items-center justify-center gap-2 shadow-lg shadow-cyan-500/25 hover:brightness-110 active:scale-95 transition-all cursor-pointer disabled:opacity-50"
            >
              <Sparkles className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
              <span>{isLoading ? 'Synthesizing with Mistral AI...' : 'Generate Lua 5.1 Script'}</span>
            </button>
          </div>

          <div className="space-y-2">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
              Quick Prompt Presets
            </span>
            <div className="space-y-1.5">
              {presets.map((item, idx) => (
                <button
                  key={idx}
                  onClick={() => setPrompt(item.prompt)}
                  className="w-full text-left p-2.5 rounded-xl bg-slate-900/50 hover:bg-slate-850 border border-slate-800 hover:border-cyan-500/30 text-xs text-slate-300 transition-all cursor-pointer flex items-center justify-between"
                >
                  <span className="font-semibold text-cyan-300">{item.label}</span>
                  <span className="text-[10px] text-slate-500 font-mono">Use &rarr;</span>
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="lg:col-span-7 bg-slate-900/60 border border-slate-800/80 rounded-2xl p-5 flex flex-col space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-slate-800">
            <div className="flex items-center gap-2">
              <Code2 className="w-4 h-4 text-cyan-400" />
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">Generated Lua 5.1 Code</h3>
            </div>
            {generatedCode && (
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                {activeModelTag}
              </span>
            )}
          </div>

          {errorMessage && (
            <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/30 text-xs text-red-400">
              {errorMessage}
            </div>
          )}

          <div className="flex-1 relative rounded-xl bg-slate-950 border border-slate-800 overflow-hidden font-mono min-h-[300px]">
            {isLoading ? (
              <div className="h-full flex flex-col items-center justify-center space-y-3 py-16 text-cyan-400">
                <Sparkles className="w-8 h-8 animate-spin" />
                <span className="text-xs font-mono">Mistral AI analyzing prompt and synthesizing Lua 5.1...</span>
              </div>
            ) : generatedCode ? (
              <textarea
                value={generatedCode}
                onChange={(e) => setGeneratedCode(e.target.value)}
                spellCheck={false}
                className="w-full h-full p-4 text-xs text-cyan-100 bg-transparent resize-none outline-none leading-5 custom-scrollbar font-mono select-text"
              />
            ) : (
              <div className="h-full flex flex-col items-center justify-center p-8 text-center text-slate-500 space-y-2">
                <Terminal className="w-8 h-8 text-slate-700" />
                <span className="text-xs">Generated Lua 5.1 script will appear here for review.</span>
                <span className="text-[11px] text-slate-600">
                  You can edit the code before inserting it into the executor or saving.
                </span>
              </div>
            )}
          </div>

          {explanation && (
            <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-xs text-slate-300 leading-relaxed">
              <span className="font-bold text-cyan-400 block mb-1">Implementation Details:</span>
              {explanation}
            </div>
          )}

          <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
            <div className="flex items-center gap-2">
              <button
                onClick={handleCopy}
                disabled={!generatedCode}
                className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-40 text-slate-200 text-xs font-semibold flex items-center gap-1.5 cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy Code'}</span>
              </button>
              <button
                onClick={handleSaveToScripts}
                disabled={!generatedCode}
                className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-40 text-slate-200 text-xs font-semibold flex items-center gap-1.5 cursor-pointer"
              >
                {savedSuccess ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Save className="w-3.5 h-3.5" />}
                <span>{savedSuccess ? 'Saved!' : 'Save Script'}</span>
              </button>
            </div>

            <button
              onClick={handleInsertIntoExecutor}
              disabled={!generatedCode}
              className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 disabled:opacity-40 text-slate-950 font-extrabold text-xs flex items-center gap-1.5 shadow-md shadow-cyan-500/25 hover:brightness-110 active:scale-95 transition-all cursor-pointer"
            >
              <ArrowDownToLine className="w-3.5 h-3.5" />
              <span>Insert into Executor</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
